import { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "fr" | "es" | "ro" | "de" | "it" | "pl";

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  en: {
    appName: "Casher",
    tagline: "Cash saver, the app that plugs your financial leaks by spotting and helping cancel unused subscriptions, so you can keep more money in your pocket!",
    getStarted: "Get Started",
    uploadCSV: "Upload CSV & Start Saving",
    viewPricing: "View Pricing",
    dashboard: "Dashboard",
    signOut: "Sign Out",
    upgradeToPro: "Upgrade to Pro",
    monthlySpending: "Monthly Spending",
    subscriptionLeaks: "Subscription Leaks",
    potentialSavings: "Potential Savings",
    savingsGoals: "Savings Goals",
    privacy: "Privacy",
    easyUpload: "Easy Upload",
    easyUploadDesc: "Simply export and upload your bank statement CSV",
    easyUploadDetails: "Works with HSBC, NatWest, Barclays, and most UK banks",
    smartAnalysis: "Smart Analysis",
    smartAnalysisDesc: "AI-powered categorization and subscription detection",
    smartAnalysisDetails: "Automatically identifies recurring payments and subscription leaks",
    saveMoney: "Save Money",
    saveMoneyDesc: "One-click cancellation links and email templates",
    saveMoneyDetails: "Get direct links to cancel subscriptions you don't use",
    howItWorks: "How It Works",
    exportCSV: "Export CSV",
    exportCSVDesc: "Download your bank statement as CSV",
    uploadFile: "Upload File",
    uploadFileDesc: "Drag and drop your CSV file",
    reviewAnalysis: "Review Analysis",
    reviewAnalysisDesc: "See your subscriptions and spending",
    cancelAndSave: "Cancel & Save",
    cancelAndSaveDesc: "One-click cancellation links",
    yourDataIsSafe: "Your Data is Safe",
    privacyDesc: "We take your privacy seriously",
    gdprCompliant: "GDPR Compliant",
    gdprDesc: "Full compliance with data protection",
    encryptedStorage: "Encrypted Storage",
    encryptedStorageDesc: "Bank-level encryption",
    autoDeletion: "Auto-Deletion",
    autoDeletionDesc: "Raw data deleted after analysis",
    disclaimer: "Disclaimer:",
    disclaimerText: "Casher provides information and tools to help you manage subscriptions. This is not financial advice. Always review your financial decisions independently.",
    allRightsReserved: "All rights reserved",
    privacyPolicy: "Privacy Policy",
    back: "Back",
    share: "Share",
    adminPanel: "Admin Panel",
  },
  fr: {
    appName: "Casher",
    tagline: "Économiseur d'argent, l'application qui colmate vos fuites financières en repérant et en aidant à annuler les abonnements inutilisés, afin que vous puissiez garder plus d'argent dans votre poche!",
    getStarted: "Commencer",
    uploadCSV: "Télécharger CSV et commencer à économiser",
    viewPricing: "Voir les tarifs",
    dashboard: "Tableau de bord",
    signOut: "Se déconnecter",
    upgradeToPro: "Passer à Pro",
    monthlySpending: "Dépenses mensuelles",
    subscriptionLeaks: "Fuites d'abonnement",
    potentialSavings: "Économies potentielles",
    savingsGoals: "Objectifs d'épargne",
    privacy: "Confidentialité",
    easyUpload: "Téléchargement facile",
    easyUploadDesc: "Exportez et téléchargez simplement votre relevé bancaire CSV",
    easyUploadDetails: "Fonctionne avec HSBC, NatWest, Barclays et la plupart des banques britanniques",
    smartAnalysis: "Analyse intelligente",
    smartAnalysisDesc: "Catégorisation et détection d'abonnements par IA",
    smartAnalysisDetails: "Identifie automatiquement les paiements récurrents et les fuites d'abonnement",
    saveMoney: "Économiser de l'argent",
    saveMoneyDesc: "Liens d'annulation en un clic et modèles d'e-mails",
    saveMoneyDetails: "Obtenez des liens directs pour annuler les abonnements que vous n'utilisez pas",
    howItWorks: "Comment ça marche",
    exportCSV: "Exporter CSV",
    exportCSVDesc: "Téléchargez votre relevé bancaire au format CSV",
    uploadFile: "Télécharger le fichier",
    uploadFileDesc: "Glissez-déposez votre fichier CSV",
    reviewAnalysis: "Examiner l'analyse",
    reviewAnalysisDesc: "Voir vos abonnements et dépenses",
    cancelAndSave: "Annuler et économiser",
    cancelAndSaveDesc: "Liens d'annulation en un clic",
    yourDataIsSafe: "Vos données sont en sécurité",
    privacyDesc: "Nous prenons votre vie privée au sérieux",
    gdprCompliant: "Conforme au RGPD",
    gdprDesc: "Conformité totale à la protection des données",
    encryptedStorage: "Stockage crypté",
    encryptedStorageDesc: "Cryptage de niveau bancaire",
    autoDeletion: "Suppression automatique",
    autoDeletionDesc: "Données brutes supprimées après analyse",
    disclaimer: "Avertissement:",
    disclaimerText: "Casher fournit des informations et des outils pour vous aider à gérer vos abonnements. Ce n'est pas un conseil financier. Examinez toujours vos décisions financières de manière indépendante.",
    allRightsReserved: "Tous droits réservés",
    privacyPolicy: "Politique de confidentialité",
    back: "Retour",
    share: "Partager",
    adminPanel: "Panneau d'administration",
  },
  es: {
    appName: "Casher",
    tagline: "Ahorrador de efectivo, la aplicación que tapa tus fugas financieras al detectar y ayudar a cancelar suscripciones no utilizadas, para que puedas mantener más dinero en tu bolsillo!",
    getStarted: "Empezar",
    uploadCSV: "Subir CSV y empezar a ahorrar",
    viewPricing: "Ver precios",
    dashboard: "Panel de control",
    signOut: "Cerrar sesión",
    upgradeToPro: "Actualizar a Pro",
    monthlySpending: "Gasto mensual",
    subscriptionLeaks: "Fugas de suscripción",
    potentialSavings: "Ahorros potenciales",
    savingsGoals: "Objetivos de ahorro",
    privacy: "Privacidad",
    easyUpload: "Carga fácil",
    easyUploadDesc: "Simplemente exporta y carga tu extracto bancario CSV",
    easyUploadDetails: "Funciona con HSBC, NatWest, Barclays y la mayoría de los bancos del Reino Unido",
    smartAnalysis: "Análisis inteligente",
    smartAnalysisDesc: "Categorización y detección de suscripciones con IA",
    smartAnalysisDetails: "Identifica automáticamente pagos recurrentes y fugas de suscripción",
    saveMoney: "Ahorrar dinero",
    saveMoneyDesc: "Enlaces de cancelación con un clic y plantillas de correo",
    saveMoneyDetails: "Obtén enlaces directos para cancelar suscripciones que no usas",
    howItWorks: "Cómo funciona",
    exportCSV: "Exportar CSV",
    exportCSVDesc: "Descarga tu extracto bancario como CSV",
    uploadFile: "Subir archivo",
    uploadFileDesc: "Arrastra y suelta tu archivo CSV",
    reviewAnalysis: "Revisar análisis",
    reviewAnalysisDesc: "Ver tus suscripciones y gastos",
    cancelAndSave: "Cancelar y ahorrar",
    cancelAndSaveDesc: "Enlaces de cancelación con un clic",
    yourDataIsSafe: "Tus datos están seguros",
    privacyDesc: "Nos tomamos tu privacidad en serio",
    gdprCompliant: "Cumple con el RGPD",
    gdprDesc: "Cumplimiento total con la protección de datos",
    encryptedStorage: "Almacenamiento encriptado",
    encryptedStorageDesc: "Encriptación de nivel bancario",
    autoDeletion: "Eliminación automática",
    autoDeletionDesc: "Datos sin procesar eliminados después del análisis",
    disclaimer: "Descargo de responsabilidad:",
    disclaimerText: "Casher proporciona información y herramientas para ayudarte a gestionar suscripciones. Esto no es asesoramiento financiero. Siempre revisa tus decisiones financieras de forma independiente.",
    allRightsReserved: "Todos los derechos reservados",
    privacyPolicy: "Política de privacidad",
    back: "Atrás",
    share: "Compartir",
    adminPanel: "Panel de administración",
  },
  ro: {
    appName: "Casher",
    tagline: "Economisitor de bani, aplicația care astupă scurgerile tale financiare prin detectarea și ajutarea la anularea abonamentelor neutilizate, astfel încât să poți păstra mai mulți bani în buzunar!",
    getStarted: "Începe acum",
    uploadCSV: "Încarcă CSV și începe să economisești",
    viewPricing: "Vezi prețurile",
    dashboard: "Tablou de bord",
    signOut: "Deconectare",
    upgradeToPro: "Actualizează la Pro",
    monthlySpending: "Cheltuieli lunare",
    subscriptionLeaks: "Scurgeri de abonamente",
    potentialSavings: "Economii potențiale",
    savingsGoals: "Obiective de economisire",
    privacy: "Confidențialitate",
    easyUpload: "Încărcare ușoară",
    easyUploadDesc: "Exportă și încarcă simplu extrasul tău bancar CSV",
    easyUploadDetails: "Funcționează cu HSBC, NatWest, Barclays și majoritatea băncilor din UK",
    smartAnalysis: "Analiză inteligentă",
    smartAnalysisDesc: "Categorizare și detectare abonamente cu AI",
    smartAnalysisDetails: "Identifică automat plățile recurente și scurgerile de abonamente",
    saveMoney: "Economisește bani",
    saveMoneyDesc: "Linkuri de anulare cu un clic și șabloane de email",
    saveMoneyDetails: "Obține linkuri directe pentru anularea abonamentelor neutilizate",
    howItWorks: "Cum funcționează",
    exportCSV: "Exportă CSV",
    exportCSVDesc: "Descarcă extrasul tău bancar ca CSV",
    uploadFile: "Încarcă fișier",
    uploadFileDesc: "Trage și plasează fișierul CSV",
    reviewAnalysis: "Revizuiește analiza",
    reviewAnalysisDesc: "Vezi abonamentele și cheltuielile tale",
    cancelAndSave: "Anulează și economisește",
    cancelAndSaveDesc: "Linkuri de anulare cu un clic",
    yourDataIsSafe: "Datele tale sunt în siguranță",
    privacyDesc: "Luăm confidențialitatea ta în serios",
    gdprCompliant: "Conform cu GDPR",
    gdprDesc: "Conformitate completă cu protecția datelor",
    encryptedStorage: "Stocare criptată",
    encryptedStorageDesc: "Criptare la nivel bancar",
    autoDeletion: "Ștergere automată",
    autoDeletionDesc: "Date brute șterse după analiză",
    disclaimer: "Declinare responsabilitate:",
    disclaimerText: "Casher oferă informații și instrumente pentru a te ajuta să gestionezi abonamentele. Aceasta nu este consultanță financiară. Revizuiește întotdeauna deciziile tale financiare în mod independent.",
    allRightsReserved: "Toate drepturile rezervate",
    privacyPolicy: "Politica de confidențialitate",
    back: "Înapoi",
    share: "Distribuie",
    adminPanel: "Panou admin",
  },
  de: {
    appName: "Casher",
    tagline: "Geldsparer, die App, die Ihre finanziellen Lecks stopft, indem sie ungenutzte Abonnements erkennt und bei der Kündigung hilft, damit Sie mehr Geld in der Tasche behalten können!",
    getStarted: "Jetzt starten",
    uploadCSV: "CSV hochladen & Sparen starten",
    viewPricing: "Preise ansehen",
    dashboard: "Dashboard",
    signOut: "Abmelden",
    upgradeToPro: "Auf Pro upgraden",
    monthlySpending: "Monatliche Ausgaben",
    subscriptionLeaks: "Abonnement-Lecks",
    potentialSavings: "Potenzielle Einsparungen",
    savingsGoals: "Sparziele",
    privacy: "Datenschutz",
    easyUpload: "Einfacher Upload",
    easyUploadDesc: "Exportieren und laden Sie einfach Ihren Kontoauszug als CSV hoch",
    easyUploadDetails: "Funktioniert mit HSBC, NatWest, Barclays und den meisten britischen Banken",
    smartAnalysis: "Intelligente Analyse",
    smartAnalysisDesc: "KI-gestützte Kategorisierung und Abonnementerkennung",
    smartAnalysisDetails: "Erkennt automatisch wiederkehrende Zahlungen und Abonnement-Lecks",
    saveMoney: "Geld sparen",
    saveMoneyDesc: "Ein-Klick-Kündigungslinks und E-Mail-Vorlagen",
    saveMoneyDetails: "Erhalten Sie direkte Links zur Kündigung ungenutzter Abonnements",
    howItWorks: "So funktioniert's",
    exportCSV: "CSV exportieren",
    exportCSVDesc: "Laden Sie Ihren Kontoauszug als CSV herunter",
    uploadFile: "Datei hochladen",
    uploadFileDesc: "Ziehen Sie Ihre CSV-Datei per Drag & Drop",
    reviewAnalysis: "Analyse überprüfen",
    reviewAnalysisDesc: "Sehen Sie Ihre Abonnements und Ausgaben",
    cancelAndSave: "Kündigen & Sparen",
    cancelAndSaveDesc: "Ein-Klick-Kündigungslinks",
    yourDataIsSafe: "Ihre Daten sind sicher",
    privacyDesc: "Wir nehmen Ihre Privatsphäre ernst",
    gdprCompliant: "DSGVO-konform",
    gdprDesc: "Vollständige Einhaltung des Datenschutzes",
    encryptedStorage: "Verschlüsselte Speicherung",
    encryptedStorageDesc: "Verschlüsselung auf Bankniveau",
    autoDeletion: "Automatische Löschung",
    autoDeletionDesc: "Rohdaten nach Analyse gelöscht",
    disclaimer: "Haftungsausschluss:",
    disclaimerText: "Casher bietet Informationen und Tools zur Verwaltung von Abonnements. Dies ist keine Finanzberatung. Überprüfen Sie Ihre finanziellen Entscheidungen immer unabhängig.",
    allRightsReserved: "Alle Rechte vorbehalten",
    privacyPolicy: "Datenschutzrichtlinie",
    back: "Zurück",
    share: "Teilen",
    adminPanel: "Admin-Panel",
  },
  it: {
    appName: "Casher",
    tagline: "Risparmiatore di denaro, l'app che chiude le tue perdite finanziarie individuando e aiutando a cancellare abbonamenti non utilizzati, così puoi tenere più soldi in tasca!",
    getStarted: "Inizia ora",
    uploadCSV: "Carica CSV e inizia a risparmiare",
    viewPricing: "Vedi prezzi",
    dashboard: "Dashboard",
    signOut: "Esci",
    upgradeToPro: "Passa a Pro",
    monthlySpending: "Spesa mensile",
    subscriptionLeaks: "Perdite di abbonamenti",
    potentialSavings: "Risparmi potenziali",
    savingsGoals: "Obiettivi di risparmio",
    privacy: "Privacy",
    easyUpload: "Caricamento facile",
    easyUploadDesc: "Esporta e carica semplicemente il tuo estratto conto CSV",
    easyUploadDetails: "Funziona con HSBC, NatWest, Barclays e la maggior parte delle banche britanniche",
    smartAnalysis: "Analisi intelligente",
    smartAnalysisDesc: "Categorizzazione e rilevamento abbonamenti con AI",
    smartAnalysisDetails: "Identifica automaticamente pagamenti ricorrenti e perdite di abbonamenti",
    saveMoney: "Risparmia denaro",
    saveMoneyDesc: "Link di cancellazione con un clic e modelli email",
    saveMoneyDetails: "Ottieni link diretti per cancellare abbonamenti non utilizzati",
    howItWorks: "Come funziona",
    exportCSV: "Esporta CSV",
    exportCSVDesc: "Scarica il tuo estratto conto come CSV",
    uploadFile: "Carica file",
    uploadFileDesc: "Trascina e rilascia il tuo file CSV",
    reviewAnalysis: "Rivedi analisi",
    reviewAnalysisDesc: "Vedi i tuoi abbonamenti e spese",
    cancelAndSave: "Cancella e risparmia",
    cancelAndSaveDesc: "Link di cancellazione con un clic",
    yourDataIsSafe: "I tuoi dati sono al sicuro",
    privacyDesc: "Prendiamo sul serio la tua privacy",
    gdprCompliant: "Conforme al GDPR",
    gdprDesc: "Piena conformità alla protezione dei dati",
    encryptedStorage: "Archiviazione crittografata",
    encryptedStorageDesc: "Crittografia di livello bancario",
    autoDeletion: "Eliminazione automatica",
    autoDeletionDesc: "Dati grezzi eliminati dopo l'analisi",
    disclaimer: "Dichiarazione di non responsabilità:",
    disclaimerText: "Casher fornisce informazioni e strumenti per aiutarti a gestire gli abbonamenti. Questo non è una consulenza finanziaria. Rivedi sempre le tue decisioni finanziarie in modo indipendente.",
    allRightsReserved: "Tutti i diritti riservati",
    privacyPolicy: "Informativa sulla privacy",
    back: "Indietro",
    share: "Condividi",
    adminPanel: "Pannello admin",
  },
  pl: {
    appName: "Casher",
    tagline: "Oszczędzacz gotówki, aplikacja, która zatyka Twoje wycieki finansowe, wykrywając i pomagając anulować niewykorzystane subskrypcje, abyś mógł zachować więcej pieniędzy w kieszeni!",
    getStarted: "Zacznij teraz",
    uploadCSV: "Wczytaj CSV i zacznij oszczędzać",
    viewPricing: "Zobacz ceny",
    dashboard: "Panel",
    signOut: "Wyloguj się",
    upgradeToPro: "Przejdź na Pro",
    monthlySpending: "Wydatki miesięczne",
    subscriptionLeaks: "Wycieki subskrypcji",
    potentialSavings: "Potencjalne oszczędności",
    savingsGoals: "Cele oszczędnościowe",
    privacy: "Prywatność",
    easyUpload: "Łatwe przesyłanie",
    easyUploadDesc: "Po prostu wyeksportuj i prześlij wyciąg bankowy CSV",
    easyUploadDetails: "Działa z HSBC, NatWest, Barclays i większością brytyjskich banków",
    smartAnalysis: "Inteligentna analiza",
    smartAnalysisDesc: "Kategoryzacja i wykrywanie subskrypcji z AI",
    smartAnalysisDetails: "Automatycznie identyfikuje płatności cykliczne i wycieki subskrypcji",
    saveMoney: "Oszczędzaj pieniądze",
    saveMoneyDesc: "Linki do anulowania jednym kliknięciem i szablony e-mail",
    saveMoneyDetails: "Uzyskaj bezpośrednie linki do anulowania niewykorzystanych subskrypcji",
    howItWorks: "Jak to działa",
    exportCSV: "Eksportuj CSV",
    exportCSVDesc: "Pobierz wyciąg bankowy jako CSV",
    uploadFile: "Prześlij plik",
    uploadFileDesc: "Przeciągnij i upuść plik CSV",
    reviewAnalysis: "Przejrzyj analizę",
    reviewAnalysisDesc: "Zobacz swoje subskrypcje i wydatki",
    cancelAndSave: "Anuluj i oszczędzaj",
    cancelAndSaveDesc: "Linki do anulowania jednym kliknięciem",
    yourDataIsSafe: "Twoje dane są bezpieczne",
    privacyDesc: "Poważnie traktujemy Twoją prywatność",
    gdprCompliant: "Zgodne z RODO",
    gdprDesc: "Pełna zgodność z ochroną danych",
    encryptedStorage: "Zaszyfrowane przechowywanie",
    encryptedStorageDesc: "Szyfrowanie na poziomie bankowym",
    autoDeletion: "Automatyczne usuwanie",
    autoDeletionDesc: "Surowe dane usuwane po analizie",
    disclaimer: "Zastrzeżenie:",
    disclaimerText: "Casher dostarcza informacje i narzędzia, które pomogą Ci zarządzać subskrypcjami. To nie jest porada finansowa. Zawsze sprawdzaj swoje decyzje finansowe niezależnie.",
    allRightsReserved: "Wszelkie prawa zastrzeżone",
    privacyPolicy: "Polityka prywatności",
    back: "Wstecz",
    share: "Udostępnij",
    adminPanel: "Panel administratora",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    if (saved) return saved as Language;
    
    const browserLang = navigator.language.split("-")[0];
    if (["fr", "es", "ro", "de", "it", "pl"].includes(browserLang)) {
      return browserLang as Language;
    }
    return "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
