import { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "fr" | "es" | "ro" | "de" | "it" | "pl";

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  en: {
    appName: "Casher",
    tagline: "Cash saver, the app that plugs your financial leaks by spotting and helping cancel unused subscriptions, so you can keep more money in your pocket!",
    getStarted: "Get Started",
    uploadCSV: "Upload CSV & Start Saving",
    viewPricing: "View Pricing",
    dashboard: "Dashboard",
    signOut: "Sign Out",
    upgradeToPro: "Upgrade to Pro",
    monthlySpending: "Monthly Spending",
    subscriptionLeaks: "Subscription Leaks",
    potentialSavings: "Potential Savings",
    savingsGoals: "Savings Goals",
    privacy: "Privacy",
    easyUpload: "Easy Upload",
    easyUploadDesc: "Simply export and upload your bank statement CSV",
    easyUploadDetails: "Works with HSBC, NatWest, Barclays, and most UK banks",
    smartAnalysis: "Smart Analysis",
    smartAnalysisDesc: "AI-powered categorization and subscription detection",
    smartAnalysisDetails: "Automatically identifies recurring payments and subscription leaks",
    saveMoney: "Save Money",
    saveMoneyDesc: "One-click cancellation links and email templates",
    saveMoneyDetails: "Get direct links to cancel subscriptions you don't use",
    howItWorks: "How It Works",
    exportCSV: "Export CSV",
    exportCSVDesc: "Download your bank statement as CSV",
    uploadFile: "Upload File",
    uploadFileDesc: "Drag and drop your CSV file",
    reviewAnalysis: "Review Analysis",
    reviewAnalysisDesc: "See your subscriptions and spending",
    cancelAndSave: "Cancel & Save",
    cancelAndSaveDesc: "One-click cancellation links",
    yourDataIsSafe: "Your Data is Safe",
    privacyDesc: "We take your privacy seriously",
    gdprCompliant: "GDPR Compliant",
    gdprDesc: "Full compliance with data protection",
    encryptedStorage: "Encrypted Storage",
    encryptedStorageDesc: "Bank-level encryption",
    autoDeletion: "Auto-Deletion",
    autoDeletionDesc: "Raw data deleted after analysis",
    disclaimer: "Disclaimer:",
    disclaimerText: "Casher provides information and tools to help you manage subscriptions. This is not financial advice. Always review your financial decisions independently.",
    allRightsReserved: "All rights reserved",
    privacyPolicy: "Privacy Policy",
    back: "Back",
    share: "Share",
    adminPanel: "Admin Panel",
    downloadApp: "Get the Casher App",
    downloadAppDesc: "Take control of your finances on the go. Download our mobile app for iOS or Android.",
    downloadIOS: "Download for iOS",
    downloadAndroid: "Download for Android",
    comingSoon: "Coming soon to App Store and Google Play",
    about: "About",
    aboutHeroTitle: "Take Control Without Compromising Security.",
    aboutHeroSubtitle: "The smartest way to find hidden subscriptions without sharing your bank passwords.",
    whyCsvTitle: "Why we will NEVER ask for your Bank Login",
    whyCsvBody: "We believe your bank credentials belong to you, and only you. Many apps ask for direct access to your accounts, creating a security risk. Casher is different. By using simple CSV uploads, we analyze your spending patterns to find leaks without ever touching your live bank account. It is simple, 100% secure, and keeps you in total control.",
    noBankLogin: "No Bank Login Required",
    noBankLoginDesc: "We never ask for your banking credentials or passwords.",
    hundredPercentSecure: "100% Secure",
    hundredPercentSecureDesc: "Your data is encrypted and never shared with third parties.",
    youInControl: "You're In Control",
    youInControlDesc: "Upload only what you want, when you want. Delete anytime.",
    missionTitle: "Defeating Subscription Fatigue",
    missionBody: "It starts with a £9.99 free trial you forgot to cancel. It ends with hundreds of pounds lost every year. Casher exists to spot those leaks instantly so you can put that money back in your pocket.",
    readyToSave: "Ready to Start Saving?",
    readyToSaveDesc: "Join thousands of users who have already discovered hidden subscriptions and saved money.",
    // Pricing page
    chooseYourPlan: "Choose Your Plan",
    startSavingToday: "Start saving money on unused subscriptions today",
    free: "Free",
    pro: "Pro",
    premium: "Premium",
    perMonth: "/month",
    mostPopular: "Most Popular",
    perfectForGettingStarted: "Perfect for getting started",
    forRegularUsers: "For regular users",
    forPowerUsers: "For power users",
    getStartedFree: "Get Started Free",
    upgradeNow: "Upgrade Now",
    featureComparison: "Feature Comparison",
    feature: "Feature",
    csvUploads: "CSV Uploads",
    onePerMonth: "1/month",
    unlimited: "Unlimited",
    transactionCategorization: "Transaction Categorization",
    subscriptionDetection: "Subscription Detection",
    advancedFilters: "Advanced Filters",
    csvExports: "CSV Exports",
    aiPoweredInsights: "AI-Powered Insights",
    support: "Support",
    community: "Community",
    email: "Email",
    priorityChat: "Priority Chat",
    getWeeklyProTips: "Get Weekly Pro Tips",
    subscribeForTips: "Subscribe to receive expert financial advice and money-saving strategies",
    enterYourEmail: "Enter your email",
    subscribe: "Subscribe",
    gdprCompliance: "All plans include GDPR-compliant data handling & multi-language support",
    cancelAnytime: "Cancel anytime, no questions asked • 30-day money-back guarantee",
    // Plan features
    oneUploadPerMonth: "1 CSV upload per month",
    basicCategorization: "Basic transaction categorization",
    viewInsights: "View insights & spot subscriptions",
    multiLanguage: "Multi-language support",
    lightDarkMode: "Light/dark mode",
    noExports: "No CSV exports",
    noAdvancedFilters: "No advanced filters",
    limitedDashboard: "Limited dashboard access",
    limitations: "Limitations:",
    unlimitedUploads: "Unlimited CSV uploads",
    advancedFiltersSearch: "Advanced filters & search",
    csvExportsFeature: "CSV exports",
    detailedReports: "Detailed spending reports",
    priorityEmailSupport: "Priority email support",
    monthlySavingsSummary: "Monthly savings summary",
    allProFeatures: "All Pro features",
    aiInsights: "AI-powered insights",
    customRecommendations: "Custom financial recommendations",
    priorityChatSupport: "Priority chat support",
    earlyAccess: "Early access to features",
    quarterlyReview: "Quarterly financial review",
  },
  fr: {
    appName: "Casher",
    tagline: "Économiseur d'argent, l'application qui colmate vos fuites financières en repérant et en aidant à annuler les abonnements inutilisés, afin que vous puissiez garder plus d'argent dans votre poche!",
    getStarted: "Commencer",
    uploadCSV: "Télécharger CSV et commencer à économiser",
    viewPricing: "Voir les tarifs",
    dashboard: "Tableau de bord",
    signOut: "Se déconnecter",
    upgradeToPro: "Passer à Pro",
    monthlySpending: "Dépenses mensuelles",
    subscriptionLeaks: "Fuites d'abonnement",
    potentialSavings: "Économies potentielles",
    savingsGoals: "Objectifs d'épargne",
    privacy: "Confidentialité",
    easyUpload: "Téléchargement facile",
    easyUploadDesc: "Exportez et téléchargez simplement votre relevé bancaire CSV",
    easyUploadDetails: "Fonctionne avec HSBC, NatWest, Barclays et la plupart des banques britanniques",
    smartAnalysis: "Analyse intelligente",
    smartAnalysisDesc: "Catégorisation et détection d'abonnements par IA",
    smartAnalysisDetails: "Identifie automatiquement les paiements récurrents et les fuites d'abonnement",
    saveMoney: "Économiser de l'argent",
    saveMoneyDesc: "Liens d'annulation en un clic et modèles d'e-mails",
    saveMoneyDetails: "Obtenez des liens directs pour annuler les abonnements que vous n'utilisez pas",
    howItWorks: "Comment ça marche",
    exportCSV: "Exporter CSV",
    exportCSVDesc: "Téléchargez votre relevé bancaire au format CSV",
    uploadFile: "Télécharger le fichier",
    uploadFileDesc: "Glissez-déposez votre fichier CSV",
    reviewAnalysis: "Examiner l'analyse",
    reviewAnalysisDesc: "Voir vos abonnements et dépenses",
    cancelAndSave: "Annuler et économiser",
    cancelAndSaveDesc: "Liens d'annulation en un clic",
    yourDataIsSafe: "Vos données sont en sécurité",
    privacyDesc: "Nous prenons votre vie privée au sérieux",
    gdprCompliant: "Conforme au RGPD",
    gdprDesc: "Conformité totale à la protection des données",
    encryptedStorage: "Stockage crypté",
    encryptedStorageDesc: "Cryptage de niveau bancaire",
    autoDeletion: "Suppression automatique",
    autoDeletionDesc: "Données brutes supprimées après analyse",
    disclaimer: "Avertissement:",
    disclaimerText: "Casher fournit des informations et des outils pour vous aider à gérer vos abonnements. Ce n'est pas un conseil financier. Examinez toujours vos décisions financières de manière indépendante.",
    allRightsReserved: "Tous droits réservés",
    privacyPolicy: "Politique de confidentialité",
    back: "Retour",
    share: "Partager",
    adminPanel: "Panneau d'administration",
    downloadApp: "Téléchargez l'application Casher",
    downloadAppDesc: "Prenez le contrôle de vos finances en déplacement. Téléchargez notre application mobile pour iOS ou Android.",
    downloadIOS: "Télécharger pour iOS",
    downloadAndroid: "Télécharger pour Android",
    comingSoon: "Bientôt disponible sur App Store et Google Play",
    about: "À propos",
    aboutHeroTitle: "Prenez le Contrôle Sans Compromettre la Sécurité.",
    aboutHeroSubtitle: "Le moyen le plus intelligent de trouver des abonnements cachés sans partager vos mots de passe bancaires.",
    whyCsvTitle: "Pourquoi nous ne demanderons JAMAIS votre identifiant bancaire",
    whyCsvBody: "Nous pensons que vos identifiants bancaires vous appartiennent, et à vous seul. De nombreuses applications demandent un accès direct à vos comptes, créant un risque de sécurité. Casher est différent. En utilisant de simples téléchargements CSV, nous analysons vos habitudes de dépenses pour trouver les fuites sans jamais toucher à votre compte bancaire. C'est simple, 100% sécurisé, et vous garde en total contrôle.",
    noBankLogin: "Pas de Connexion Bancaire Requise",
    noBankLoginDesc: "Nous ne demandons jamais vos identifiants ou mots de passe bancaires.",
    hundredPercentSecure: "100% Sécurisé",
    hundredPercentSecureDesc: "Vos données sont cryptées et jamais partagées avec des tiers.",
    youInControl: "Vous Êtes en Contrôle",
    youInControlDesc: "Téléchargez seulement ce que vous voulez, quand vous le voulez. Supprimez à tout moment.",
    missionTitle: "Vaincre la Fatigue des Abonnements",
    missionBody: "Cela commence par un essai gratuit de 9,99 £ que vous avez oublié d'annuler. Cela se termine par des centaines de livres perdues chaque année. Casher existe pour repérer ces fuites instantanément afin que vous puissiez remettre cet argent dans votre poche.",
    readyToSave: "Prêt à Commencer à Économiser?",
    readyToSaveDesc: "Rejoignez des milliers d'utilisateurs qui ont déjà découvert des abonnements cachés et économisé de l'argent.",
    // Pricing page
    chooseYourPlan: "Choisissez Votre Plan",
    startSavingToday: "Commencez à économiser sur les abonnements inutilisés dès aujourd'hui",
    free: "Gratuit",
    pro: "Pro",
    premium: "Premium",
    perMonth: "/mois",
    mostPopular: "Le Plus Populaire",
    perfectForGettingStarted: "Parfait pour commencer",
    forRegularUsers: "Pour les utilisateurs réguliers",
    forPowerUsers: "Pour les utilisateurs avancés",
    getStartedFree: "Commencer Gratuitement",
    upgradeNow: "Mettre à Niveau",
    featureComparison: "Comparaison des Fonctionnalités",
    feature: "Fonctionnalité",
    csvUploads: "Téléchargements CSV",
    onePerMonth: "1/mois",
    unlimited: "Illimité",
    transactionCategorization: "Catégorisation des Transactions",
    subscriptionDetection: "Détection d'Abonnements",
    advancedFilters: "Filtres Avancés",
    csvExports: "Exports CSV",
    aiPoweredInsights: "Insights IA",
    support: "Support",
    community: "Communauté",
    email: "Email",
    priorityChat: "Chat Prioritaire",
    getWeeklyProTips: "Recevez des Conseils Pro Hebdomadaires",
    subscribeForTips: "Abonnez-vous pour recevoir des conseils financiers experts et des stratégies d'économie",
    enterYourEmail: "Entrez votre email",
    subscribe: "S'abonner",
    gdprCompliance: "Tous les plans incluent le traitement des données conforme au RGPD et le support multilingue",
    cancelAnytime: "Annulez à tout moment, sans questions • Garantie de remboursement de 30 jours",
    // Plan features
    oneUploadPerMonth: "1 téléchargement CSV par mois",
    basicCategorization: "Catégorisation de base des transactions",
    viewInsights: "Voir les insights et repérer les abonnements",
    multiLanguage: "Support multilingue",
    lightDarkMode: "Mode clair/sombre",
    noExports: "Pas d'exports CSV",
    noAdvancedFilters: "Pas de filtres avancés",
    limitedDashboard: "Accès limité au tableau de bord",
    limitations: "Limitations:",
    unlimitedUploads: "Téléchargements CSV illimités",
    advancedFiltersSearch: "Filtres avancés et recherche",
    csvExportsFeature: "Exports CSV",
    detailedReports: "Rapports de dépenses détaillés",
    priorityEmailSupport: "Support email prioritaire",
    monthlySavingsSummary: "Résumé mensuel des économies",
    allProFeatures: "Toutes les fonctionnalités Pro",
    aiInsights: "Insights alimentés par l'IA",
    customRecommendations: "Recommandations financières personnalisées",
    priorityChatSupport: "Support chat prioritaire",
    earlyAccess: "Accès anticipé aux fonctionnalités",
    quarterlyReview: "Bilan financier trimestriel",
  },
  es: {
    appName: "Casher",
    tagline: "Ahorrador de efectivo, la aplicación que tapa tus fugas financieras al detectar y ayudar a cancelar suscripciones no utilizadas, para que puedas mantener más dinero en tu bolsillo!",
    getStarted: "Empezar",
    uploadCSV: "Subir CSV y empezar a ahorrar",
    viewPricing: "Ver precios",
    dashboard: "Panel de control",
    signOut: "Cerrar sesión",
    upgradeToPro: "Actualizar a Pro",
    monthlySpending: "Gasto mensual",
    subscriptionLeaks: "Fugas de suscripción",
    potentialSavings: "Ahorros potenciales",
    savingsGoals: "Objetivos de ahorro",
    privacy: "Privacidad",
    easyUpload: "Carga fácil",
    easyUploadDesc: "Simplemente exporta y carga tu extracto bancario CSV",
    easyUploadDetails: "Funciona con HSBC, NatWest, Barclays y la mayoría de los bancos del Reino Unido",
    smartAnalysis: "Análisis inteligente",
    smartAnalysisDesc: "Categorización y detección de suscripciones con IA",
    smartAnalysisDetails: "Identifica automáticamente pagos recurrentes y fugas de suscripción",
    saveMoney: "Ahorrar dinero",
    saveMoneyDesc: "Enlaces de cancelación con un clic y plantillas de correo",
    saveMoneyDetails: "Obtén enlaces directos para cancelar suscripciones que no usas",
    howItWorks: "Cómo funciona",
    exportCSV: "Exportar CSV",
    exportCSVDesc: "Descarga tu extracto bancario como CSV",
    uploadFile: "Subir archivo",
    uploadFileDesc: "Arrastra y suelta tu archivo CSV",
    reviewAnalysis: "Revisar análisis",
    reviewAnalysisDesc: "Ver tus suscripciones y gastos",
    cancelAndSave: "Cancelar y ahorrar",
    cancelAndSaveDesc: "Enlaces de cancelación con un clic",
    yourDataIsSafe: "Tus datos están seguros",
    privacyDesc: "Nos tomamos tu privacidad en serio",
    gdprCompliant: "Cumple con el RGPD",
    gdprDesc: "Cumplimiento total con la protección de datos",
    encryptedStorage: "Almacenamiento encriptado",
    encryptedStorageDesc: "Encriptación de nivel bancario",
    autoDeletion: "Eliminación automática",
    autoDeletionDesc: "Datos sin procesar eliminados después del análisis",
    disclaimer: "Descargo de responsabilidad:",
    disclaimerText: "Casher proporciona información y herramientas para ayudarte a gestionar suscripciones. Esto no es asesoramiento financiero. Siempre revisa tus decisiones financieras de forma independiente.",
    allRightsReserved: "Todos los derechos reservados",
    privacyPolicy: "Política de privacidad",
    back: "Atrás",
    share: "Compartir",
    adminPanel: "Panel de administración",
    downloadApp: "Descarga la aplicación Casher",
    downloadAppDesc: "Toma el control de tus finanzas sobre la marcha. Descarga nuestra aplicación móvil para iOS o Android.",
    downloadIOS: "Descargar para iOS",
    downloadAndroid: "Descargar para Android",
    comingSoon: "Próximamente en App Store y Google Play",
    about: "Acerca de",
    aboutHeroTitle: "Toma el Control Sin Comprometer la Seguridad.",
    aboutHeroSubtitle: "La forma más inteligente de encontrar suscripciones ocultas sin compartir tus contraseñas bancarias.",
    whyCsvTitle: "Por qué NUNCA pediremos tu inicio de sesión bancario",
    whyCsvBody: "Creemos que tus credenciales bancarias te pertenecen, y solo a ti. Muchas aplicaciones piden acceso directo a tus cuentas, creando un riesgo de seguridad. Casher es diferente. Al usar cargas CSV simples, analizamos tus patrones de gasto para encontrar fugas sin tocar nunca tu cuenta bancaria activa. Es simple, 100% seguro, y te mantiene en total control.",
    noBankLogin: "No Se Requiere Inicio de Sesión Bancario",
    noBankLoginDesc: "Nunca pedimos tus credenciales o contraseñas bancarias.",
    hundredPercentSecure: "100% Seguro",
    hundredPercentSecureDesc: "Tus datos están encriptados y nunca se comparten con terceros.",
    youInControl: "Tú Tienes el Control",
    youInControlDesc: "Sube solo lo que quieras, cuando quieras. Elimina en cualquier momento.",
    missionTitle: "Derrotando la Fatiga de Suscripciones",
    missionBody: "Comienza con una prueba gratuita de £9.99 que olvidaste cancelar. Termina con cientos de libras perdidas cada año. Casher existe para detectar esas fugas al instante para que puedas poner ese dinero de vuelta en tu bolsillo.",
    readyToSave: "¿Listo para Empezar a Ahorrar?",
    readyToSaveDesc: "Únete a miles de usuarios que ya han descubierto suscripciones ocultas y ahorrado dinero.",
    // Pricing page
    chooseYourPlan: "Elige Tu Plan",
    startSavingToday: "Empieza a ahorrar en suscripciones no utilizadas hoy",
    free: "Gratis",
    pro: "Pro",
    premium: "Premium",
    perMonth: "/mes",
    mostPopular: "Más Popular",
    perfectForGettingStarted: "Perfecto para empezar",
    forRegularUsers: "Para usuarios regulares",
    forPowerUsers: "Para usuarios avanzados",
    getStartedFree: "Empezar Gratis",
    upgradeNow: "Actualizar Ahora",
    featureComparison: "Comparación de Funciones",
    feature: "Función",
    csvUploads: "Cargas CSV",
    onePerMonth: "1/mes",
    unlimited: "Ilimitado",
    transactionCategorization: "Categorización de Transacciones",
    subscriptionDetection: "Detección de Suscripciones",
    advancedFilters: "Filtros Avanzados",
    csvExports: "Exportaciones CSV",
    aiPoweredInsights: "Insights con IA",
    support: "Soporte",
    community: "Comunidad",
    email: "Email",
    priorityChat: "Chat Prioritario",
    getWeeklyProTips: "Recibe Consejos Pro Semanales",
    subscribeForTips: "Suscríbete para recibir consejos financieros expertos y estrategias de ahorro",
    enterYourEmail: "Ingresa tu email",
    subscribe: "Suscribirse",
    gdprCompliance: "Todos los planes incluyen manejo de datos conforme al RGPD y soporte multilingüe",
    cancelAnytime: "Cancela en cualquier momento, sin preguntas • Garantía de devolución de 30 días",
    // Plan features
    oneUploadPerMonth: "1 carga CSV por mes",
    basicCategorization: "Categorización básica de transacciones",
    viewInsights: "Ver insights y detectar suscripciones",
    multiLanguage: "Soporte multilingüe",
    lightDarkMode: "Modo claro/oscuro",
    noExports: "Sin exportaciones CSV",
    noAdvancedFilters: "Sin filtros avanzados",
    limitedDashboard: "Acceso limitado al panel",
    limitations: "Limitaciones:",
    unlimitedUploads: "Cargas CSV ilimitadas",
    advancedFiltersSearch: "Filtros avanzados y búsqueda",
    csvExportsFeature: "Exportaciones CSV",
    detailedReports: "Informes de gastos detallados",
    priorityEmailSupport: "Soporte por email prioritario",
    monthlySavingsSummary: "Resumen mensual de ahorros",
    allProFeatures: "Todas las funciones Pro",
    aiInsights: "Insights con inteligencia artificial",
    customRecommendations: "Recomendaciones financieras personalizadas",
    priorityChatSupport: "Soporte por chat prioritario",
    earlyAccess: "Acceso anticipado a funciones",
    quarterlyReview: "Revisión financiera trimestral",
  },
  ro: {
    appName: "Casher",
    tagline: "Economisitor de bani, aplicația care astupă scurgerile tale financiare prin detectarea și ajutarea la anularea abonamentelor neutilizate, astfel încât să poți păstra mai mulți bani în buzunar!",
    getStarted: "Începe acum",
    uploadCSV: "Încarcă CSV și începe să economisești",
    viewPricing: "Vezi prețurile",
    dashboard: "Tablou de bord",
    signOut: "Deconectare",
    upgradeToPro: "Actualizează la Pro",
    monthlySpending: "Cheltuieli lunare",
    subscriptionLeaks: "Scurgeri de abonamente",
    potentialSavings: "Economii potențiale",
    savingsGoals: "Obiective de economisire",
    privacy: "Confidențialitate",
    easyUpload: "Încărcare ușoară",
    easyUploadDesc: "Exportă și încarcă simplu extrasul tău bancar CSV",
    easyUploadDetails: "Funcționează cu HSBC, NatWest, Barclays și majoritatea băncilor din UK",
    smartAnalysis: "Analiză inteligentă",
    smartAnalysisDesc: "Categorizare și detectare abonamente cu AI",
    smartAnalysisDetails: "Identifică automat plățile recurente și scurgerile de abonamente",
    saveMoney: "Economisește bani",
    saveMoneyDesc: "Linkuri de anulare cu un clic și șabloane de email",
    saveMoneyDetails: "Obține linkuri directe pentru anularea abonamentelor neutilizate",
    howItWorks: "Cum funcționează",
    exportCSV: "Exportă CSV",
    exportCSVDesc: "Descarcă extrasul tău bancar ca CSV",
    uploadFile: "Încarcă fișier",
    uploadFileDesc: "Trage și plasează fișierul CSV",
    reviewAnalysis: "Revizuiește analiza",
    reviewAnalysisDesc: "Vezi abonamentele și cheltuielile tale",
    cancelAndSave: "Anulează și economisește",
    cancelAndSaveDesc: "Linkuri de anulare cu un clic",
    yourDataIsSafe: "Datele tale sunt în siguranță",
    privacyDesc: "Luăm confidențialitatea ta în serios",
    gdprCompliant: "Conform cu GDPR",
    gdprDesc: "Conformitate completă cu protecția datelor",
    encryptedStorage: "Stocare criptată",
    encryptedStorageDesc: "Criptare la nivel bancar",
    autoDeletion: "Ștergere automată",
    autoDeletionDesc: "Date brute șterse după analiză",
    disclaimer: "Declinare responsabilitate:",
    disclaimerText: "Casher oferă informații și instrumente pentru a te ajuta să gestionezi abonamentele. Aceasta nu este consultanță financiară. Revizuiește întotdeauna deciziile tale financiare în mod independent.",
    allRightsReserved: "Toate drepturile rezervate",
    privacyPolicy: "Politica de confidențialitate",
    back: "Înapoi",
    share: "Distribuie",
    adminPanel: "Panou admin",
    downloadApp: "Descarcă aplicația Casher",
    downloadAppDesc: "Preia controlul finanțelor tale din mers. Descarcă aplicația noastră mobilă pentru iOS sau Android.",
    downloadIOS: "Descarcă pentru iOS",
    downloadAndroid: "Descarcă pentru Android",
    comingSoon: "În curând pe App Store și Google Play",
    about: "Despre",
    aboutHeroTitle: "Preia Controlul Fără a Compromite Securitatea.",
    aboutHeroSubtitle: "Cel mai inteligent mod de a găsi abonamente ascunse fără a partaja parolele bancare.",
    whyCsvTitle: "De ce nu vom cere NICIODATĂ datele tale bancare",
    whyCsvBody: "Credem că datele tale bancare îți aparțin doar ție. Multe aplicații cer acces direct la conturile tale, creând un risc de securitate. Casher este diferit. Folosind simple încărcări CSV, analizăm tiparele tale de cheltuieli pentru a găsi scurgeri fără a atinge vreodată contul tău bancar activ. Este simplu, 100% sigur și îți oferă control total.",
    noBankLogin: "Nu Este Necesar Login Bancar",
    noBankLoginDesc: "Nu cerem niciodată datele sau parolele tale bancare.",
    hundredPercentSecure: "100% Sigur",
    hundredPercentSecureDesc: "Datele tale sunt criptate și nu sunt partajate cu terți.",
    youInControl: "Tu Ai Controlul",
    youInControlDesc: "Încarcă doar ce vrei, când vrei. Șterge oricând.",
    missionTitle: "Înfrângerea Oboselii de Abonamente",
    missionBody: "Începe cu o încercare gratuită de £9.99 pe care ai uitat să o anulezi. Se termină cu sute de lire pierdute în fiecare an. Casher există pentru a detecta aceste scurgeri instantaneu, astfel încât să poți pune acei bani înapoi în buzunar.",
    readyToSave: "Pregătit să Începi să Economisești?",
    readyToSaveDesc: "Alătură-te miilor de utilizatori care au descoperit deja abonamente ascunse și au economisit bani.",
    // Pricing page
    chooseYourPlan: "Alege-ți Planul",
    startSavingToday: "Începe să economisești pe abonamentele neutilizate astăzi",
    free: "Gratuit",
    pro: "Pro",
    premium: "Premium",
    perMonth: "/lună",
    mostPopular: "Cel Mai Popular",
    perfectForGettingStarted: "Perfect pentru început",
    forRegularUsers: "Pentru utilizatori obișnuiți",
    forPowerUsers: "Pentru utilizatori avansați",
    getStartedFree: "Începe Gratuit",
    upgradeNow: "Actualizează Acum",
    featureComparison: "Comparație Funcționalități",
    feature: "Funcționalitate",
    csvUploads: "Încărcări CSV",
    onePerMonth: "1/lună",
    unlimited: "Nelimitat",
    transactionCategorization: "Categorizare Tranzacții",
    subscriptionDetection: "Detectare Abonamente",
    advancedFilters: "Filtre Avansate",
    csvExports: "Exporturi CSV",
    aiPoweredInsights: "Insights cu AI",
    support: "Suport",
    community: "Comunitate",
    email: "Email",
    priorityChat: "Chat Prioritar",
    getWeeklyProTips: "Primește Sfaturi Pro Săptămânale",
    subscribeForTips: "Abonează-te pentru a primi sfaturi financiare de la experți și strategii de economisire",
    enterYourEmail: "Introdu emailul tău",
    subscribe: "Abonează-te",
    gdprCompliance: "Toate planurile includ gestionarea datelor conform GDPR și suport multilingv",
    cancelAnytime: "Anulează oricând, fără întrebări • Garanție de rambursare de 30 de zile",
    // Plan features
    oneUploadPerMonth: "1 încărcare CSV pe lună",
    basicCategorization: "Categorizare de bază a tranzacțiilor",
    viewInsights: "Vezi insights și detectează abonamentele",
    multiLanguage: "Suport multilingv",
    lightDarkMode: "Mod luminos/întunecat",
    noExports: "Fără exporturi CSV",
    noAdvancedFilters: "Fără filtre avansate",
    limitedDashboard: "Acces limitat la tablou",
    limitations: "Limitări:",
    unlimitedUploads: "Încărcări CSV nelimitate",
    advancedFiltersSearch: "Filtre avansate și căutare",
    csvExportsFeature: "Exporturi CSV",
    detailedReports: "Rapoarte detaliate de cheltuieli",
    priorityEmailSupport: "Suport email prioritar",
    monthlySavingsSummary: "Rezumat lunar al economiilor",
    allProFeatures: "Toate funcționalitățile Pro",
    aiInsights: "Insights cu inteligență artificială",
    customRecommendations: "Recomandări financiare personalizate",
    priorityChatSupport: "Suport chat prioritar",
    earlyAccess: "Acces timpuriu la funcționalități",
    quarterlyReview: "Revizuire financiară trimestrială",
  },
  de: {
    appName: "Casher",
    tagline: "Geldsparer, die App, die Ihre finanziellen Lecks stopft, indem sie ungenutzte Abonnements erkennt und bei der Kündigung hilft, damit Sie mehr Geld in der Tasche behalten können!",
    getStarted: "Jetzt starten",
    uploadCSV: "CSV hochladen & Sparen starten",
    viewPricing: "Preise ansehen",
    dashboard: "Dashboard",
    signOut: "Abmelden",
    upgradeToPro: "Auf Pro upgraden",
    monthlySpending: "Monatliche Ausgaben",
    subscriptionLeaks: "Abonnement-Lecks",
    potentialSavings: "Potenzielle Einsparungen",
    savingsGoals: "Sparziele",
    privacy: "Datenschutz",
    easyUpload: "Einfacher Upload",
    easyUploadDesc: "Exportieren und laden Sie einfach Ihren Kontoauszug als CSV hoch",
    easyUploadDetails: "Funktioniert mit HSBC, NatWest, Barclays und den meisten britischen Banken",
    smartAnalysis: "Intelligente Analyse",
    smartAnalysisDesc: "KI-gestützte Kategorisierung und Abonnementerkennung",
    smartAnalysisDetails: "Erkennt automatisch wiederkehrende Zahlungen und Abonnement-Lecks",
    saveMoney: "Geld sparen",
    saveMoneyDesc: "Ein-Klick-Kündigungslinks und E-Mail-Vorlagen",
    saveMoneyDetails: "Erhalten Sie direkte Links zur Kündigung ungenutzter Abonnements",
    howItWorks: "So funktioniert's",
    exportCSV: "CSV exportieren",
    exportCSVDesc: "Laden Sie Ihren Kontoauszug als CSV herunter",
    uploadFile: "Datei hochladen",
    uploadFileDesc: "Ziehen Sie Ihre CSV-Datei per Drag & Drop",
    reviewAnalysis: "Analyse überprüfen",
    reviewAnalysisDesc: "Sehen Sie Ihre Abonnements und Ausgaben",
    cancelAndSave: "Kündigen & Sparen",
    cancelAndSaveDesc: "Ein-Klick-Kündigungslinks",
    yourDataIsSafe: "Ihre Daten sind sicher",
    privacyDesc: "Wir nehmen Ihre Privatsphäre ernst",
    gdprCompliant: "DSGVO-konform",
    gdprDesc: "Vollständige Einhaltung des Datenschutzes",
    encryptedStorage: "Verschlüsselte Speicherung",
    encryptedStorageDesc: "Verschlüsselung auf Bankniveau",
    autoDeletion: "Automatische Löschung",
    autoDeletionDesc: "Rohdaten nach Analyse gelöscht",
    disclaimer: "Haftungsausschluss:",
    disclaimerText: "Casher bietet Informationen und Tools zur Verwaltung von Abonnements. Dies ist keine Finanzberatung. Überprüfen Sie Ihre finanziellen Entscheidungen immer unabhängig.",
    allRightsReserved: "Alle Rechte vorbehalten",
    privacyPolicy: "Datenschutzrichtlinie",
    back: "Zurück",
    share: "Teilen",
    adminPanel: "Admin-Panel",
    downloadApp: "Holen Sie sich die Casher App",
    downloadAppDesc: "Behalten Sie Ihre Finanzen unterwegs im Griff. Laden Sie unsere mobile App für iOS oder Android herunter.",
    downloadIOS: "Für iOS herunterladen",
    downloadAndroid: "Für Android herunterladen",
    comingSoon: "Bald im App Store und bei Google Play",
    about: "Über uns",
    aboutHeroTitle: "Behalten Sie die Kontrolle Ohne Kompromisse bei der Sicherheit.",
    aboutHeroSubtitle: "Der intelligenteste Weg, versteckte Abonnements zu finden, ohne Ihre Bankpasswörter zu teilen.",
    whyCsvTitle: "Warum wir NIEMALS nach Ihrem Bank-Login fragen werden",
    whyCsvBody: "Wir glauben, dass Ihre Bankdaten Ihnen gehören, und nur Ihnen. Viele Apps verlangen direkten Zugang zu Ihren Konten und schaffen damit ein Sicherheitsrisiko. Casher ist anders. Durch einfache CSV-Uploads analysieren wir Ihre Ausgabemuster, um Lecks zu finden, ohne jemals Ihr aktives Bankkonto zu berühren. Es ist einfach, 100% sicher und hält Sie in voller Kontrolle.",
    noBankLogin: "Kein Bank-Login Erforderlich",
    noBankLoginDesc: "Wir fragen niemals nach Ihren Bankdaten oder Passwörtern.",
    hundredPercentSecure: "100% Sicher",
    hundredPercentSecureDesc: "Ihre Daten sind verschlüsselt und werden niemals mit Dritten geteilt.",
    youInControl: "Sie Haben die Kontrolle",
    youInControlDesc: "Laden Sie nur hoch, was Sie wollen, wann Sie wollen. Löschen Sie jederzeit.",
    missionTitle: "Abonnement-Müdigkeit Besiegen",
    missionBody: "Es beginnt mit einer £9,99 kostenlosen Testversion, die Sie vergessen haben zu kündigen. Es endet mit Hunderten von Pfund, die jedes Jahr verloren gehen. Casher existiert, um diese Lecks sofort zu erkennen, damit Sie das Geld wieder in Ihre Tasche stecken können.",
    readyToSave: "Bereit zu Sparen?",
    readyToSaveDesc: "Schließen Sie sich Tausenden von Nutzern an, die bereits versteckte Abonnements entdeckt und Geld gespart haben.",
    // Pricing page
    chooseYourPlan: "Wählen Sie Ihren Plan",
    startSavingToday: "Beginnen Sie heute, bei ungenutzten Abonnements zu sparen",
    free: "Kostenlos",
    pro: "Pro",
    premium: "Premium",
    perMonth: "/Monat",
    mostPopular: "Am Beliebtesten",
    perfectForGettingStarted: "Perfekt zum Starten",
    forRegularUsers: "Für regelmäßige Nutzer",
    forPowerUsers: "Für Power-Nutzer",
    getStartedFree: "Kostenlos Starten",
    upgradeNow: "Jetzt Upgraden",
    featureComparison: "Funktionsvergleich",
    feature: "Funktion",
    csvUploads: "CSV-Uploads",
    onePerMonth: "1/Monat",
    unlimited: "Unbegrenzt",
    transactionCategorization: "Transaktionskategorisierung",
    subscriptionDetection: "Abonnementerkennung",
    advancedFilters: "Erweiterte Filter",
    csvExports: "CSV-Exporte",
    aiPoweredInsights: "KI-gestützte Insights",
    support: "Support",
    community: "Community",
    email: "E-Mail",
    priorityChat: "Prioritäts-Chat",
    getWeeklyProTips: "Wöchentliche Pro-Tipps Erhalten",
    subscribeForTips: "Abonnieren Sie für Finanzexpertentipps und Sparstrategien",
    enterYourEmail: "E-Mail eingeben",
    subscribe: "Abonnieren",
    gdprCompliance: "Alle Pläne beinhalten DSGVO-konforme Datenverarbeitung und mehrsprachige Unterstützung",
    cancelAnytime: "Jederzeit kündbar, ohne Fragen • 30-Tage-Geld-zurück-Garantie",
    // Plan features
    oneUploadPerMonth: "1 CSV-Upload pro Monat",
    basicCategorization: "Grundlegende Transaktionskategorisierung",
    viewInsights: "Insights anzeigen und Abonnements erkennen",
    multiLanguage: "Mehrsprachige Unterstützung",
    lightDarkMode: "Hell/Dunkel-Modus",
    noExports: "Keine CSV-Exporte",
    noAdvancedFilters: "Keine erweiterten Filter",
    limitedDashboard: "Eingeschränkter Dashboard-Zugang",
    limitations: "Einschränkungen:",
    unlimitedUploads: "Unbegrenzte CSV-Uploads",
    advancedFiltersSearch: "Erweiterte Filter und Suche",
    csvExportsFeature: "CSV-Exporte",
    detailedReports: "Detaillierte Ausgabenberichte",
    priorityEmailSupport: "Prioritäts-E-Mail-Support",
    monthlySavingsSummary: "Monatliche Sparübersicht",
    allProFeatures: "Alle Pro-Funktionen",
    aiInsights: "KI-gestützte Insights",
    customRecommendations: "Individuelle Finanzempfehlungen",
    priorityChatSupport: "Prioritäts-Chat-Support",
    earlyAccess: "Früher Zugang zu Funktionen",
    quarterlyReview: "Vierteljährliche Finanzprüfung",
  },
  it: {
    appName: "Casher",
    tagline: "Risparmiatore di denaro, l'app che chiude le tue perdite finanziarie individuando e aiutando a cancellare abbonamenti non utilizzati, così puoi tenere più soldi in tasca!",
    getStarted: "Inizia ora",
    uploadCSV: "Carica CSV e inizia a risparmiare",
    viewPricing: "Vedi prezzi",
    dashboard: "Dashboard",
    signOut: "Esci",
    upgradeToPro: "Passa a Pro",
    monthlySpending: "Spesa mensile",
    subscriptionLeaks: "Perdite di abbonamenti",
    potentialSavings: "Risparmi potenziali",
    savingsGoals: "Obiettivi di risparmio",
    privacy: "Privacy",
    easyUpload: "Caricamento facile",
    easyUploadDesc: "Esporta e carica semplicemente il tuo estratto conto CSV",
    easyUploadDetails: "Funziona con HSBC, NatWest, Barclays e la maggior parte delle banche britanniche",
    smartAnalysis: "Analisi intelligente",
    smartAnalysisDesc: "Categorizzazione e rilevamento abbonamenti con AI",
    smartAnalysisDetails: "Identifica automaticamente pagamenti ricorrenti e perdite di abbonamenti",
    saveMoney: "Risparmia denaro",
    saveMoneyDesc: "Link di cancellazione con un clic e modelli email",
    saveMoneyDetails: "Ottieni link diretti per cancellare abbonamenti non utilizzati",
    howItWorks: "Come funziona",
    exportCSV: "Esporta CSV",
    exportCSVDesc: "Scarica il tuo estratto conto come CSV",
    uploadFile: "Carica file",
    uploadFileDesc: "Trascina e rilascia il tuo file CSV",
    reviewAnalysis: "Rivedi analisi",
    reviewAnalysisDesc: "Vedi i tuoi abbonamenti e spese",
    cancelAndSave: "Cancella e risparmia",
    cancelAndSaveDesc: "Link di cancellazione con un clic",
    yourDataIsSafe: "I tuoi dati sono al sicuro",
    privacyDesc: "Prendiamo sul serio la tua privacy",
    gdprCompliant: "Conforme al GDPR",
    gdprDesc: "Piena conformità alla protezione dei dati",
    encryptedStorage: "Archiviazione crittografata",
    encryptedStorageDesc: "Crittografia di livello bancario",
    autoDeletion: "Eliminazione automatica",
    autoDeletionDesc: "Dati grezzi eliminati dopo l'analisi",
    disclaimer: "Dichiarazione di non responsabilità:",
    disclaimerText: "Casher fornisce informazioni e strumenti per aiutarti a gestire gli abbonamenti. Questo non è una consulenza finanziaria. Rivedi sempre le tue decisioni finanziarie in modo indipendente.",
    allRightsReserved: "Tutti i diritti riservati",
    privacyPolicy: "Informativa sulla privacy",
    back: "Indietro",
    share: "Condividi",
    adminPanel: "Pannello admin",
    downloadApp: "Scarica l'app Casher",
    downloadAppDesc: "Prendi il controllo delle tue finanze in movimento. Scarica la nostra app mobile per iOS o Android.",
    downloadIOS: "Scarica per iOS",
    downloadAndroid: "Scarica per Android",
    comingSoon: "Prossimamente su App Store e Google Play",
    about: "Chi siamo",
    aboutHeroTitle: "Prendi il Controllo Senza Compromettere la Sicurezza.",
    aboutHeroSubtitle: "Il modo più intelligente per trovare abbonamenti nascosti senza condividere le tue password bancarie.",
    whyCsvTitle: "Perché NON chiederemo MAI il tuo accesso bancario",
    whyCsvBody: "Crediamo che le tue credenziali bancarie appartengano a te, e solo a te. Molte app richiedono accesso diretto ai tuoi conti, creando un rischio per la sicurezza. Casher è diverso. Utilizzando semplici caricamenti CSV, analizziamo i tuoi modelli di spesa per trovare perdite senza mai toccare il tuo conto bancario attivo. È semplice, 100% sicuro e ti mantiene in totale controllo.",
    noBankLogin: "Nessun Accesso Bancario Richiesto",
    noBankLoginDesc: "Non chiediamo mai le tue credenziali o password bancarie.",
    hundredPercentSecure: "100% Sicuro",
    hundredPercentSecureDesc: "I tuoi dati sono crittografati e mai condivisi con terze parti.",
    youInControl: "Sei Tu al Comando",
    youInControlDesc: "Carica solo ciò che vuoi, quando vuoi. Elimina in qualsiasi momento.",
    missionTitle: "Sconfiggere la Stanchezza degli Abbonamenti",
    missionBody: "Inizia con una prova gratuita di £9,99 che hai dimenticato di annullare. Finisce con centinaia di sterline perse ogni anno. Casher esiste per individuare quelle perdite all'istante così puoi rimettere quei soldi in tasca.",
    readyToSave: "Pronto a Iniziare a Risparmiare?",
    readyToSaveDesc: "Unisciti a migliaia di utenti che hanno già scoperto abbonamenti nascosti e risparmiato denaro.",
    // Pricing page
    chooseYourPlan: "Scegli il Tuo Piano",
    startSavingToday: "Inizia a risparmiare sugli abbonamenti inutilizzati oggi",
    free: "Gratuito",
    pro: "Pro",
    premium: "Premium",
    perMonth: "/mese",
    mostPopular: "Più Popolare",
    perfectForGettingStarted: "Perfetto per iniziare",
    forRegularUsers: "Per utenti regolari",
    forPowerUsers: "Per utenti avanzati",
    getStartedFree: "Inizia Gratis",
    upgradeNow: "Aggiorna Ora",
    featureComparison: "Confronto Funzionalità",
    feature: "Funzionalità",
    csvUploads: "Caricamenti CSV",
    onePerMonth: "1/mese",
    unlimited: "Illimitato",
    transactionCategorization: "Categorizzazione Transazioni",
    subscriptionDetection: "Rilevamento Abbonamenti",
    advancedFilters: "Filtri Avanzati",
    csvExports: "Esportazioni CSV",
    aiPoweredInsights: "Insights con AI",
    support: "Supporto",
    community: "Comunità",
    email: "Email",
    priorityChat: "Chat Prioritaria",
    getWeeklyProTips: "Ricevi Consigli Pro Settimanali",
    subscribeForTips: "Iscriviti per ricevere consigli finanziari esperti e strategie di risparmio",
    enterYourEmail: "Inserisci la tua email",
    subscribe: "Iscriviti",
    gdprCompliance: "Tutti i piani includono gestione dati conforme al GDPR e supporto multilingue",
    cancelAnytime: "Annulla in qualsiasi momento, senza domande • Garanzia di rimborso di 30 giorni",
    // Plan features
    oneUploadPerMonth: "1 caricamento CSV al mese",
    basicCategorization: "Categorizzazione base delle transazioni",
    viewInsights: "Visualizza insights e rileva abbonamenti",
    multiLanguage: "Supporto multilingue",
    lightDarkMode: "Modalità chiara/scura",
    noExports: "Nessuna esportazione CSV",
    noAdvancedFilters: "Nessun filtro avanzato",
    limitedDashboard: "Accesso limitato alla dashboard",
    limitations: "Limitazioni:",
    unlimitedUploads: "Caricamenti CSV illimitati",
    advancedFiltersSearch: "Filtri avanzati e ricerca",
    csvExportsFeature: "Esportazioni CSV",
    detailedReports: "Report di spesa dettagliati",
    priorityEmailSupport: "Supporto email prioritario",
    monthlySavingsSummary: "Riepilogo risparmi mensile",
    allProFeatures: "Tutte le funzionalità Pro",
    aiInsights: "Insights con intelligenza artificiale",
    customRecommendations: "Raccomandazioni finanziarie personalizzate",
    priorityChatSupport: "Supporto chat prioritario",
    earlyAccess: "Accesso anticipato alle funzionalità",
    quarterlyReview: "Revisione finanziaria trimestrale",
  },
  pl: {
    appName: "Casher",
    tagline: "Oszczędzacz gotówki, aplikacja, która zatyka Twoje wycieki finansowe, wykrywając i pomagając anulować niewykorzystane subskrypcje, abyś mógł zachować więcej pieniędzy w kieszeni!",
    getStarted: "Zacznij teraz",
    uploadCSV: "Wczytaj CSV i zacznij oszczędzać",
    viewPricing: "Zobacz ceny",
    dashboard: "Panel",
    signOut: "Wyloguj się",
    upgradeToPro: "Przejdź na Pro",
    monthlySpending: "Wydatki miesięczne",
    subscriptionLeaks: "Wycieki subskrypcji",
    potentialSavings: "Potencjalne oszczędności",
    savingsGoals: "Cele oszczędnościowe",
    privacy: "Prywatność",
    easyUpload: "Łatwe przesyłanie",
    easyUploadDesc: "Po prostu wyeksportuj i prześlij wyciąg bankowy CSV",
    easyUploadDetails: "Działa z HSBC, NatWest, Barclays i większością brytyjskich banków",
    smartAnalysis: "Inteligentna analiza",
    smartAnalysisDesc: "Kategoryzacja i wykrywanie subskrypcji z AI",
    smartAnalysisDetails: "Automatycznie identyfikuje płatności cykliczne i wycieki subskrypcji",
    saveMoney: "Oszczędzaj pieniądze",
    saveMoneyDesc: "Linki do anulowania jednym kliknięciem i szablony e-mail",
    saveMoneyDetails: "Uzyskaj bezpośrednie linki do anulowania niewykorzystanych subskrypcji",
    howItWorks: "Jak to działa",
    exportCSV: "Eksportuj CSV",
    exportCSVDesc: "Pobierz wyciąg bankowy jako CSV",
    uploadFile: "Prześlij plik",
    uploadFileDesc: "Przeciągnij i upuść plik CSV",
    reviewAnalysis: "Przejrzyj analizę",
    reviewAnalysisDesc: "Zobacz swoje subskrypcje i wydatki",
    cancelAndSave: "Anuluj i oszczędzaj",
    cancelAndSaveDesc: "Linki do anulowania jednym kliknięciem",
    yourDataIsSafe: "Twoje dane są bezpieczne",
    privacyDesc: "Poważnie traktujemy Twoją prywatność",
    gdprCompliant: "Zgodne z RODO",
    gdprDesc: "Pełna zgodność z ochroną danych",
    encryptedStorage: "Zaszyfrowane przechowywanie",
    encryptedStorageDesc: "Szyfrowanie na poziomie bankowym",
    autoDeletion: "Automatyczne usuwanie",
    autoDeletionDesc: "Surowe dane usuwane po analizie",
    disclaimer: "Zastrzeżenie:",
    disclaimerText: "Casher dostarcza informacje i narzędzia, które pomogą Ci zarządzać subskrypcjami. To nie jest porada finansowa. Zawsze sprawdzaj swoje decyzje finansowe niezależnie.",
    allRightsReserved: "Wszelkie prawa zastrzeżone",
    privacyPolicy: "Polityka prywatności",
    back: "Wstecz",
    share: "Udostępnij",
    adminPanel: "Panel administratora",
    downloadApp: "Pobierz aplikację Casher",
    downloadAppDesc: "Przejmij kontrolę nad swoimi finansami w podróży. Pobierz naszą aplikację mobilną na iOS lub Android.",
    downloadIOS: "Pobierz na iOS",
    downloadAndroid: "Pobierz na Android",
    comingSoon: "Wkrótce w App Store i Google Play",
    about: "O nas",
    aboutHeroTitle: "Przejmij Kontrolę Bez Kompromisów w Bezpieczeństwie.",
    aboutHeroSubtitle: "Najinteligentniejszy sposób na znalezienie ukrytych subskrypcji bez udostępniania haseł bankowych.",
    whyCsvTitle: "Dlaczego NIGDY nie poprosimy o Twój login bankowy",
    whyCsvBody: "Wierzymy, że Twoje dane bankowe należą do Ciebie i tylko do Ciebie. Wiele aplikacji prosi o bezpośredni dostęp do Twoich kont, tworząc ryzyko bezpieczeństwa. Casher jest inny. Używając prostych przesyłów CSV, analizujemy Twoje wzorce wydatków, aby znaleźć wycieki bez dotykania Twojego aktywnego konta bankowego. Jest to proste, 100% bezpieczne i daje Ci pełną kontrolę.",
    noBankLogin: "Nie Wymaga Logowania Bankowego",
    noBankLoginDesc: "Nigdy nie prosimy o Twoje dane logowania lub hasła bankowe.",
    hundredPercentSecure: "100% Bezpieczne",
    hundredPercentSecureDesc: "Twoje dane są zaszyfrowane i nigdy nie są udostępniane stronom trzecim.",
    youInControl: "Masz Pełną Kontrolę",
    youInControlDesc: "Przesyłaj tylko to, co chcesz, kiedy chcesz. Usuń w dowolnym momencie.",
    missionTitle: "Pokonując Zmęczenie Subskrypcjami",
    missionBody: "Zaczyna się od bezpłatnego okresu próbnego za £9,99, który zapomniałeś anulować. Kończy się setkami funtów traconych każdego roku. Casher istnieje, aby natychmiast wykryć te wycieki, abyś mógł włożyć te pieniądze z powrotem do kieszeni.",
    readyToSave: "Gotowy Zacząć Oszczędzać?",
    readyToSaveDesc: "Dołącz do tysięcy użytkowników, którzy już odkryli ukryte subskrypcje i zaoszczędzili pieniądze.",
    // Pricing page
    chooseYourPlan: "Wybierz Swój Plan",
    startSavingToday: "Zacznij oszczędzać na niewykorzystanych subskrypcjach już dziś",
    free: "Darmowy",
    pro: "Pro",
    premium: "Premium",
    perMonth: "/miesiąc",
    mostPopular: "Najpopularniejszy",
    perfectForGettingStarted: "Idealny na początek",
    forRegularUsers: "Dla regularnych użytkowników",
    forPowerUsers: "Dla zaawansowanych użytkowników",
    getStartedFree: "Zacznij Za Darmo",
    upgradeNow: "Ulepsz Teraz",
    featureComparison: "Porównanie Funkcji",
    feature: "Funkcja",
    csvUploads: "Przesyłanie CSV",
    onePerMonth: "1/miesiąc",
    unlimited: "Bez limitu",
    transactionCategorization: "Kategoryzacja Transakcji",
    subscriptionDetection: "Wykrywanie Subskrypcji",
    advancedFilters: "Zaawansowane Filtry",
    csvExports: "Eksport CSV",
    aiPoweredInsights: "Insights z AI",
    support: "Wsparcie",
    community: "Społeczność",
    email: "Email",
    priorityChat: "Priorytetowy Chat",
    getWeeklyProTips: "Otrzymuj Cotygodniowe Porady Pro",
    subscribeForTips: "Zapisz się, aby otrzymywać eksperckie porady finansowe i strategie oszczędzania",
    enterYourEmail: "Wprowadź swój email",
    subscribe: "Zapisz się",
    gdprCompliance: "Wszystkie plany obejmują przetwarzanie danych zgodne z RODO i wsparcie wielojęzyczne",
    cancelAnytime: "Anuluj w dowolnym momencie, bez pytań • 30-dniowa gwarancja zwrotu pieniędzy",
    // Plan features
    oneUploadPerMonth: "1 przesłanie CSV miesięcznie",
    basicCategorization: "Podstawowa kategoryzacja transakcji",
    viewInsights: "Przeglądaj insights i wykrywaj subskrypcje",
    multiLanguage: "Wsparcie wielojęzyczne",
    lightDarkMode: "Tryb jasny/ciemny",
    noExports: "Brak eksportu CSV",
    noAdvancedFilters: "Brak zaawansowanych filtrów",
    limitedDashboard: "Ograniczony dostęp do panelu",
    limitations: "Ograniczenia:",
    unlimitedUploads: "Nieograniczone przesyłanie CSV",
    advancedFiltersSearch: "Zaawansowane filtry i wyszukiwanie",
    csvExportsFeature: "Eksport CSV",
    detailedReports: "Szczegółowe raporty wydatków",
    priorityEmailSupport: "Priorytetowe wsparcie email",
    monthlySavingsSummary: "Miesięczne podsumowanie oszczędności",
    allProFeatures: "Wszystkie funkcje Pro",
    aiInsights: "Insights z wykorzystaniem AI",
    customRecommendations: "Spersonalizowane rekomendacje finansowe",
    priorityChatSupport: "Priorytetowe wsparcie na czacie",
    earlyAccess: "Wczesny dostęp do funkcji",
    quarterlyReview: "Kwartalny przegląd finansowy",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    if (saved) return saved as Language;
    
    const browserLang = navigator.language.split("-")[0];
    if (["fr", "es", "ro", "de", "it", "pl"].includes(browserLang)) {
      return browserLang as Language;
    }
    return "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
