export const user = { id: '00000000-0000-4000-8000-000000000001', aud: 'authenticated', role: 'authenticated', email: 'audit@example.test', app_metadata: { provider: 'email', providers: ['email'] }, user_metadata: {}, created_at: '2026-01-01T00:00:00Z' };
export function makeFixtures() {
  const now = new Date();
  const month = (offset) => new Date(Date.UTC(now.getFullYear(), now.getMonth() + offset, 1)).toISOString().slice(0, 7);
  const categories = [['Rent', 950], ['Groceries', 213.42], ['Subscription', 34.98], ['Transport', 82.1], ['Dining', 64.5], ['Fitness', 35], ['Utilities', 113], ['Shopping', 23.19], ['Other', 7.5]];
  const transactions = [-1, 0].flatMap(offset => categories.map(([category, amount], index) => ({ id: `transaction-${offset}-${index}`, user_id: user.id, date: `${month(offset)}-02`, description: category === 'Subscription' ? 'Netflix and Spotify' : `Example ${category.toLowerCase()} payment`, amount: -amount * (offset === -1 ? 1.1 : 1), category, direction: 'debit' })));
  transactions.push({ id: 'income', user_id: user.id, date: `${month(0)}-01`, description: 'Example salary', amount: 3200, category: 'Income', direction: 'credit' });
  const subscriptions = [['Netflix', 12.99, 'monthly'], ['Spotify', 11.99, 'monthly'], ['Cloud storage annual', 120, 'annual'], ['Fitness membership with a long service name', 35, 'monthly']].map(([service_name, amount, frequency], index) => ({ id: `subscription-${index}`, user_id: user.id, service_name, amount, frequency, estimated_annual_cost: amount * (frequency === 'monthly' ? 12 : 1), status: 'active', created_at: `${month(-1)}-01T12:00:00Z`, last_charged: `${month(0)}-02`, cancellation_url: null }));
  return { transactions, detected_subscriptions: subscriptions, profiles: [{ user_id: user.id, subscription_tier: 'pro', monthly_uploads_used: 2, uploads_reset_date: `${month(0)}-01`, monthly_spending_history: [{ month: month(-1), spending: 1900 }] }], user_roles: [], savings_goals: [], upload_history: [{ id: 'upload-1', user_id: user.id, upload_date: `${month(0)}-03T12:00:00Z`, created_at: `${month(0)}-03T12:00:00Z`, total_spending: 3199.55, potential_savings: 800, subscriptions_count: 4, transaction_count: transactions.length }], subscription_plans: [] };
}
