import { Link } from 'react-router-dom';
import SEO from '@/components/SEO';
import { Button } from '@/components/ui/button';

export default function Terms() {
  return <div className="min-h-screen bg-background">
    <SEO title="Terms of Service — Casher" description="How Casher works, subscription charges, cancellation and your rights." path="/terms" />
    <header className="border-b px-4 py-4"><Button asChild variant="ghost"><Link to="/" aria-label="Back to Casher"><span aria-hidden="true">Back to Casher</span></Link></Button></header>
    <main className="mx-auto max-w-3xl space-y-8 px-4 py-10 text-sm leading-7">
      <h1 className="text-4xl font-semibold">Terms of Service</h1>
      <p className="text-muted-foreground">Last updated: 7 September 2026</p>
      <section className="space-y-3"><h2 className="text-xl font-semibold">Using Casher</h2><p>Casher helps you review spending and possible recurring payments from GBP bank statements you upload. You must be at least 18 and upload only data you are entitled to use. Keep your account secure and contact <a className="underline" href="mailto:privacy@trycasher.com">privacy@trycasher.com</a> if you suspect unauthorised access.</p><p>Categories and recurring-payment suggestions can be wrong. Check them against your original statement. Totals cover imported records, not your bank balance. Casher does not give financial advice, move money or cancel contracts with other service providers.</p></section>
      <section className="space-y-3"><h2 className="text-xl font-semibold">Plans and renewal</h2><p>The Free plan includes one CSV upload per calendar month. New Pro subscriptions are currently paused. The Pro plan price is £9.99 per month, renewing monthly until cancelled when enrolment is available. There is no free Pro trial. The checkout shows the amount due before you pay. Upload allowances reset at the beginning of each calendar month in UTC. Premium and automatic bank connections are unavailable and are not included in a Pro purchase.</p><p>Stripe processes web subscription payments and stores your payment details. Paying for Pro does not connect a bank account. The mobile companion app has no in-app purchases.</p></section>
      <section className="space-y-3"><h2 className="text-xl font-semibold">Cancellation and payment problems</h2><p>You can stop renewal through Billing in the web app. Cancellation normally takes effect at the end of your paid billing period, with access continuing until then. Cancelling Casher does not cancel subscriptions identified in your statements. If a payment fails, Pro access is suspended while the payment is overdue. Your imported records remain available; update your payment method in Billing to resolve the failed payment.</p><p>To exercise any applicable cooling-off right or request a refund, contact privacy@trycasher.com with the email used for your Casher account and the date of purchase. Do not send card details. Statutory cancellation and refund rights are unaffected by these terms.</p></section>
      <section className="space-y-3"><h2 className="text-xl font-semibold">Your data and account</h2><p>Our <Link className="underline" to="/privacy" aria-label="Privacy Policy"><span aria-hidden="true">Privacy Policy</span></Link> explains processing, retention and deletion. Every plan can export saved dashboard data and delete an account in Account settings. Account deletion cancels any active Casher subscription immediately and ends remaining access. Contact privacy@trycasher.com for other personal-data requests or if deletion cannot be completed. Deleting the app from a device does not delete your Casher account or cancel a subscription.</p></section>
      <section className="space-y-3"><h2 className="text-xl font-semibold">Availability and fair use</h2><p>Service may be interrupted by maintenance or provider outages. Do not attempt to access another person's records, bypass upload limits, upload malicious files or disrupt the service. We may restrict access where needed to protect accounts or investigate abuse. Nothing here excludes liability or consumer rights that cannot lawfully be excluded.</p></section>
      <section className="space-y-3"><h2 className="text-xl font-semibold">Changes and contact</h2><p>Material changes to a paid plan or these terms will be communicated before they take effect. Contact privacy@trycasher.com for support, cancellation or complaints.</p></section>
    </main>
  </div>;
}
